services:
  app:
    image: josemanuel343/php-app:1.0
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-8081}:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DB_NAME:-appdb}
      - DB_USER=${DB_USER:-appuser}
      - DB_PASS=${DB_PASS:-apppassword}
    networks:
      - app-net
    depends_on:
      - db

  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      # Defaults will be used when .env is not provided; instructors can create .env to override
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-ChangeMeRootPass123!}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-appdb}
      - MYSQL_USER=${MYSQL_USER:-appuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-apppassword}
    volumes:
      - db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d:ro
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  db-data:
